# Generated by Django 5.2.1 on 2025-08-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brands", "0002_brand_created_brand_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brand",
            name="image_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
