# Generated by Django 5.2.4 on 2025-07-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoiceitem",
            name="price",
            field=models.PositiveBigIntegerField(),
        ),
    ]
