# Generated by Django 5.2.4 on 2025-07-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_alter_category_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="order",
            field=models.PositiveBigIntegerField(default=5),
        ),
    ]
