# Generated by Django 5.2.5 on 2025-08-15 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.PositiveBigIntegerField(default=64),
        ),
    ]
