# Generated by Django 5.2.5 on 2025-08-17 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0004_alter_category_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="order",
            field=models.CharField(max_length=3),
        ),
    ]
