# Generated by Django 5.2.1 on 2025-08-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0006_category_created_category_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="first_page",
            field=models.BooleanField(default=True),
        ),
    ]
