# Generated by Django 5.2.1 on 2025-09-05 03:53

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0007_alter_category_first_page"),
        ("products", "0010_product_image_urls"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParameterGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameter_groups",
                        to="categories.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("text_value", models.TextField(null=True)),
                ("boolean_value", models.BooleanField(default=False, null=True)),
                (
                    "selectable_vallue",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=300),
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TX", "TEXT"),
                            ("BL", "BOOLEAN"),
                            ("SL", "SELECTABLE"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="products.product",
                    ),
                ),
                (
                    "parameter_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parameters.parametergroup",
                    ),
                ),
            ],
        ),
    ]
