# Generated by Django 5.2.1 on 2025-09-05 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parameters", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parameter",
            old_name="selectable_vallue",
            new_name="selectable_vallues",
        ),
    ]
