# Generated by Django 5.2.1 on 2025-09-05 04:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parameters", "0002_rename_selectable_vallue_parameter_selectable_vallues"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parameter",
            name="selectable_vallues",
        ),
        migrations.AddField(
            model_name="parameter",
            name="selectable_values",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=300), default=[], size=None
            ),
            preserve_default=False,
        ),
    ]
