# Generated by Django 5.2.1 on 2025-09-05 15:19

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parameters", "0003_remove_parameter_selectable_vallues_and_more"),
        ("products", "0010_product_image_urls"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parameter",
            old_name="type",
            new_name="filed_type",
        ),
        migrations.RemoveField(
            model_name="parameter",
            name="boolean_value",
        ),
        migrations.RemoveField(
            model_name="parameter",
            name="product",
        ),
        migrations.RemoveField(
            model_name="parameter",
            name="selectable_values",
        ),
        migrations.RemoveField(
            model_name="parameter",
            name="text_value",
        ),
        migrations.CreateModel(
            name="ProductParameterValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_value", models.CharField(blank=True, max_length=200, null=True)),
                ("bool_value", models.BooleanField(blank=True, null=True)),
                (
                    "selectable_values",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=300), size=None
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parameters.parameter",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
