# Generated by Django 5.2.1 on 2025-09-05 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parameters", "0004_rename_type_parameter_filed_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parameter",
            old_name="filed_type",
            new_name="field_type",
        ),
    ]
