# Generated by Django 5.2.1 on 2025-09-05 17:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parameters", "0005_rename_filed_type_parameter_field_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productparametervalue",
            name="selectable_values",
        ),
        migrations.AddField(
            model_name="parameter",
            name="selectable_values",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=300), null=True, size=None
            ),
        ),
        migrations.AddField(
            model_name="productparametervalue",
            name="selectable_value",
            field=models.CharField(max_length=300, null=True),
        ),
    ]
