# Generated by Django 5.2.1 on 2025-09-05 18:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parameters", "0006_remove_productparametervalue_selectable_values_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parameter",
            name="selectable_values",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=300),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
