# Generated by Django 5.2.1 on 2025-09-08 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parameters", "0007_alter_parameter_selectable_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productparametervalue",
            name="parameter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="values",
                to="parameters.parameter",
            ),
        ),
    ]
