# Generated by Django 5.2.1 on 2025-09-08 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parameters", "0008_alter_productparametervalue_parameter"),
        ("products", "0010_product_image_urls"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productparametervalue",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parameter_values",
                to="products.product",
            ),
        ),
    ]
