# Generated by Django 5.2.1 on 2025-09-08 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parameters", "0009_alter_productparametervalue_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productparametervalue",
            name="selectable_value",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
