# Generated by Django 5.2.1 on 2025-09-08 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parameters", "0010_alter_productparametervalue_selectable_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parameter",
            name="parameter_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parameters",
                to="parameters.parametergroup",
            ),
        ),
    ]
