# Generated by Django 5.2.4 on 2025-07-18 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("advantages", "0001_initial"),
        ("brands", "0001_initial"),
        ("categories", "0001_initial"),
        ("disadvantages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("info", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("image_url", models.TextField(blank=True, null=True)),
                ("price", models.IntegerField()),
                ("count", models.IntegerField()),
                (
                    "advantages",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="advantages.advantage"
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="brands.brand",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="categories.category",
                    ),
                ),
                (
                    "disadvantages",
                    models.ManyToManyField(
                        blank=True,
                        related_name="products",
                        to="disadvantages.disadvantage",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
