# Generated by Django 5.2.1 on 2025-08-28 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="generated",
            field=models.BooleanField(default=False),
        ),
    ]
