# Generated by Django 5.2.1 on 2025-08-28 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entities", "0001_initial"),
        ("products", "0003_product_generated"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="entities.entity",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="main_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_products",
                to="products.product",
            ),
        ),
    ]
