# Generated by Django 5.2.1 on 2025-08-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_entity_product_main_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="info",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
