# Generated by Django 5.2.1 on 2025-08-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_alter_product_count_alter_product_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="generatable",
            field=models.BooleanField(default=False),
        ),
    ]
