# Generated by Django 5.2.1 on 2025-08-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advantages", "0001_initial"),
        ("brands", "0003_brand_description_brand_image_url"),
        ("categories", "0007_alter_category_first_page"),
        ("disadvantages", "0002_disadvantage_created_disadvantage_updated"),
        ("entities", "0002_entity_english_name"),
        ("products", "0006_product_generatable"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="price2",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="price3",
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("main_product", "entity"), name="unique_main_entity_product"
            ),
        ),
    ]
