# Generated by Django 5.2.1 on 2025-08-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_product_price2_product_price3_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price2",
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="price3",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
