# Generated by Django 5.2.1 on 2025-08-30 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0007_alter_category_first_page"),
        ("products", "0008_alter_product_price_alter_product_price2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="categories.category",
            ),
        ),
    ]
