# Generated by Django 5.2.1 on 2025-09-01 12:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_urls",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=500),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
