# Generated by Django 5.2.1 on 2025-09-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("products", "0010_product_image_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(related_name="products", to="images.image"),
        ),
    ]
